JOBSTREET_MAPPING = {
        "Administrasi & Dukungan Perkantoran": "human_resources_and_administration",
        "Akuntasi": "finance_and_insurance",
        "Asuransi & Dana Pensiun": "finance_and_insurance",
        "Call Center & Layanan Konsumen": "sales_and_marketing",
        "CEO & Manajemen Umum": "human_resources_and_administration",
        "Desain & Arsitektur": "arts_entertainment_and_media",
        "Hospitaliti & Pariwisata": "hospitality_and_tourism",
        "Hukum": "legal",
        "Kesehatan & Medis": "healthcare_and_social_assistance",
        "Keterampilan & Jasa": "human_resources_and_administration",
        "Konstruksi": "construction",
        "Konsultasi & Strategi": "public_administration_and_government",
        "Layanan & Pengembangan Masyarakat": "public_administration_and_government",
        "Manufaktur, Transportasi & Logistik": "manufacturing",
        "Olahraga & Rekreasi": "arts_entertainment_and_media",
        "Pekerjaan Lepas": "human_resources_and_administration",
        "Pemasaran & Komunikasi": "sales_and_marketing",
        "Pemerintahan & Pertahanan": "public_administration_and_government",
        "Pendidikan & Pelatihan": "education_and_training",
        "Penjualan": "sales_and_marketing",
        "Perbankan & Layanan Finansial": "finance_and_insurance",
        "Periklanan, Seni & Media": "arts_entertainment_and_media",
        "Pertambangan, Sumber Daya Alam & Energi": "science_and_research",
        "Petanian, Hewan & Konservasi": "science_and_research",
        "Real Estat & Properti": "construction",
        "Ritel & Produk Konsumen": "retail",
        "Sains & Teknologi": "science_and_research",
        "Sumber Daya Manusia & Perekrutan": "human_resources_and_administration",
        "Teknik": "engineering",
        "Teknologi Informasi & Komunikasi": "information_technology"
}

GLINTS_MAPPING = {
    "Administrative & HR & Accounting": "human_resources_and_administration",
    "Arts, Media, & Communications": "arts_entertainment_and_media",
    "Aviation & Maritime": "transportation_and_logistics",
    "Building & Real Estate": "construction",
    "Business Development & Sales": "sales_and_marketing",
    "Computer & Technology": "information_and_communication_technology",
    "Design": "arts_entertainment_and_media",
    "Education & Training": "education_and_training",
    "Finance": "finance_and_insurance",
    "Healthcare": "healthcare_and_social_assistance",
    "Leadership & Senior Management": "public_administration_and_government",
    "Legal, Consulting & Translation": "legal",
    "Manufacturing & Production": "manufacturing",
    "Marketing": "sales_and_marketing",
    "Operations": "manufacturing",
    "Others": "others",
    "Product Management & Project Management": "information_and_communication_technology",
    "Purchasing, Procurement & Trade": "retail",
    "Science & Research": "science_and_research",
    "Services Industry": "hospitality_and_tourism",
    "Supply Chain, Logistics & Transportation": "transportation_and_logistics"
}